print("*"*50)
name = input("请输入姓名：")
company = input("请输入公司：")
title = input("请输入职位：")
phone = input("请输入电话：")
emial = input("请输入邮箱：")
print("*"*50)
print("company\n")
print("name（tiltle）\n")
print("电话:phone")
print("邮箱:emial")
print("*"*50)
